apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: back-training-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-training-app
  template:
    metadata:
      labels:
        app: back-training-app
    spec:
      containers:
      - name: backend
        image: axelpereira/k8s-training-test-app-back:1.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: MONGO_HOST
        - name: MONGO_PORT 
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: MONGO_PORT
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: MONGO_DB
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: MONGO_PASSWORD
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 3  # Démarre après 3 secondes
          periodSeconds: 5        # Vérifie toutes les 5 secondes
          failureThreshold: 3     # Échoue après 3 échecs
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10  # Démarre après 10 secondes
          periodSeconds: 5         # Vérifie toutes les 5 secondes
          failureThreshold: 2      # Redémarre après 2 échecs consécutifs
      restartPolicy: Always